import { defineConfig } from "vitest/config";

const TEST_DATABASE_URL =
  process.env.TEST_DATABASE_URL ??
  "postgresql://postgres@localhost:5432/timetracker_test";

export default defineConfig({
  resolve: {
    alias: [
      // @workspace/api-zod is generated by Orval in Zod v4 syntax while the
      // workspace installs Zod v3; lib/api-zod/tsconfig.json shims this for the
      // type checker, and this is the same shim at runtime. Production gets
      // away without it only because esbuild tree-shakes the v4-only schemas
      // that no route imports.
      { find: /^zod$/, replacement: "zod/v4" },
    ],
  },
  test: {
    // Set before any test module loads, so config.ts validates against the
    // throwaway test database rather than a developer's working one.
    env: {
      NODE_ENV: "test",
      DATABASE_URL: TEST_DATABASE_URL,
      DATABASE_SSL: "false",
      SESSION_SECRET: "test-only-secret",
      LOG_LEVEL: "silent",
      PORT: "8099",
      // Points token verification at the local key server the Entra suite
      // stands up, so the real jose verification path runs without a tenant.
      ENTRA_TENANT_ID: "00000000-0000-0000-0000-000000000000",
      ENTRA_AUDIENCE: "api://timetrack-test",
      // The scope a connector asks for. Absent here, the MCP discovery
      // document advertised no scopes at all and nothing noticed, because
      // production sets it and the suite did not.
      ENTRA_API_SCOPE: "api://timetrack-test/access_as_user",
      ENTRA_ISSUER: "https://test-issuer.local/v2.0",
      ENTRA_JWKS_URI: "http://127.0.0.1:8098/keys",
      // The /dev console answers 404 to everyone unless somebody is listed.
      DEV_CONSOLE_EMAILS: "md@test.local",
      // Gives request rows a stable replica name to assert on.
      CONTAINER_APP_REPLICA_NAME: "test-replica",
      // The MCP endpoint answers 404 without its own address, so the suite
      // has to give it one to test anything else about it.
      MCP_PUBLIC_URL: "https://timetrack.test.local/mcp",
    },
    globalSetup: ["./test/global-setup.ts"],
    // The suite shares one database, so files run sequentially rather than
    // racing each other's fixtures.
    fileParallelism: false,
    testTimeout: 20_000,
    hookTimeout: 60_000,
    include: ["test/**/*.test.ts"],
  },
});
